var msg = "Hello world";
console.log(msg);
var age = 10;
var _name = "foo";
var wage = 100.0;
var active = true;
console.log("age = ", age);
console.log("_name = ", _name);
console.log("wage = ", wage);
console.log("active = ", active);
var msg2 = "foobar";
var msg3 = "bim";
console.log("msg2 = ", msg2);
console.log("msg3 = ", msg3);
